FROM python:3.13

WORKDIR /app 

COPY ./requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

COPY ./app /app/app

#RUN pip install --no-cache-dir --upgrade uvicorn

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]

# CREDENCIALES ADMINER
#myapidb myapi myapi myapi